apiVersion: v2
name: sonarqube
description: SonarQube offers Code Quality and Code Security analysis for up to 27 languages. Find Bugs, Vulnerabilities, Security Hotspots and Code Smells throughout your workflow.
type: application
version: 8.0.6-bb.4
appVersion: 9.9.6
keywords:
  - coverage
  - security
  - code
  - quality
home: https://www.sonarqube.org/
icon: https://www.sonarqube.org/assets/logo-31ad3115b1b4b120f3d1efd63e6b13ac9f1f89437f0cf6881cc4d8b5603a52b4.svg
sources:
  - https://github.com/SonarSource/docker-sonarqube
  - https://github.com/SonarSource/sonarqube
kubeVersion: '>= 1.19.0-0'
maintainers:
  - name: leo-geoffroy-sonarsource
    email: leo.geoffroy+helm@sonarsource.com
  - name: carminevassallo
    email: carmine.vassallo@sonarsource.com
  - name: jCOTINEAU
    email: jeremy.cotineau@sonarsource.com
  - name: davividal
    email: davi.koscianski-vidal@sonarsource.com
annotations:
  artifacthub.io/links: |
    - name: support
      url: https://community.sonarsource.com/
    - name: Chart Source
      url: https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube
  artifacthub.io/changes: |
    - kind: changed
      description: "Update SonarQube to 9.9.6"
  artifacthub.io/containsSecurityUpdates: "false"
  bigbang.dev/upstreamReleaseNotesMarkdown: |
    - [Find our upstream chart's CHANGELOG here](https://github.com/SonarSource/helm-chart-sonarqube/blob/sonarqube-8.0.6-sonarqube-dce-7.0.6/charts/sonarqube-dce/CHANGELOG.md)
    - [and our upstream application release notes here](https://github.com/SonarSource/helm-chart-sonarqube/blob/sonarqube-8.0.6-sonarqube-dce-7.0.6/charts/sonarqube-dce/README.md)
  bigbang.dev/applicationVersions: |
    - Sonarqube: 9.9.6-community
  artifacthub.io/images: |
    - name: sonarqube
      image: sonarqube:9.9.6-community
  helm.sh/images: |
    - name: sonarqube
      image: registry1.dso.mil/ironbank/big-bang/sonarqube-9:9.9.6-community
    - name: base
      image: registry1.dso.mil/ironbank/big-bang/base:2.1.0
    - name: postgresql12
      condition: postgresql.enabled
      image: registry1.dso.mil/ironbank/opensource/postgres/postgresql12:12.19
dependencies:
  - name: postgresql
    version: 8.6.4
    repository: file://./deps/postgresql
    condition: postgresql.enabled
  - name: gluon
    version: '0.5.0'
    repository: 'oci://registry1.dso.mil/bigbang'
