apiVersion: v2
name: sonarqube
description: SonarQube is a self-managed, automatic code review tool that systematically helps you deliver clean code. As a core element of our Sonar solution, SonarQube integrates into your existing workflow and detects issues in your code to help you perform continuous code inspections of your projects. The tool analyses 30+ different programming languages and integrates into your CI pipeline and DevOps platform to ensure that your code meets high-quality standards.
type: application
version: 10.7.0-bb.3
appVersion: 10.7.0
keywords:
- coverage
- security
- code
- quality
home: https://www.sonarqube.org/
icon: https://raw.githubusercontent.com/SonarSource/sonarqube-static-resources/master/helm/SonarQubeLogo.svg
sources:
- https://github.com/SonarSource/helm-chart-sonarqube
- https://github.com/SonarSource/docker-sonarqube
- https://github.com/SonarSource/sonarqube
kubeVersion: '>= 1.24.0-0'
maintainers:
- name: leo-geoffroy-sonarsource
  email: leo.geoffroy+helm@sonarsource.com
- name: carminevassallo
  email: carmine.vassallo@sonarsource.com
- name: jCOTINEAU
  email: jeremy.cotineau@sonarsource.com
- name: davividal
  email: davi.koscianski-vidal@sonarsource.com
annotations:
  bigbang.dev/maintenanceTrack: bb_integrated
  artifacthub.io/links: |
    - name: support
      url: https://community.sonarsource.com/
    - name: Chart Source
      url: https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube
  artifacthub.io/changes: |
    - kind: changed
      description: "Update Chart's version to 10.6.1"
    - kind: fixed
      description: "Fix typo in the new STS template"
    - kind: fixed
      description: "Fix regression on env valuesFrom in the new STS template"
  artifacthub.io/containsSecurityUpdates: "false"
  bigbang.dev/upstreamReleaseNotesMarkdown: |
    - [Find our upstream chart's CHANGELOG here](https://github.com/SonarSource/helm-chart-sonarqube/blob/sonarqube-8.0.6-sonarqube-dce-7.0.6/charts/sonarqube-dce/CHANGELOG.md)
    - [and our upstream application release notes here](https://github.com/SonarSource/helm-chart-sonarqube/blob/sonarqube-8.0.6-sonarqube-dce-7.0.6/charts/sonarqube-dce/README.md)
  bigbang.dev/applicationVersions: |
    - Sonarqube: 10.7.0-community
  artifacthub.io/images: |
    - name: sonarqube
      image: sonarqube:10.7.0-community
  helm.sh/images: |
    - name: sonarqube
      image: registry1.dso.mil/ironbank/big-bang/sonarqube-10:10.7.0-community
    - name: base
      image: registry1.dso.mil/ironbank/big-bang/base:2.1.0
    - name: postgresql
      condition: postgresql.enabled
      image: registry1.dso.mil/ironbank/opensource/postgres/postgresql:16.2
dependencies:
- name: postgresql
  version: '15.2.10'
  repository: 'oci://registry-1.docker.io/bitnamicharts' 
  condition: postgresql.enabled
- name: gluon
  version: '0.5.14'
  repository: 'oci://registry1.dso.mil/bigbang'
