apiVersion: v2
name: sonarqube
description: SonarQube is a self-managed, automatic code review tool that systematically helps you deliver clean code. As a core element of our Sonar solution, SonarQube integrates into your existing workflow and detects issues in your code to help you perform continuous code inspections of your projects. The tool analyses 30+ different programming languages and integrates into your CI pipeline and DevOps platform to ensure that your code meets high-quality standards.
type: application
version: 2025.4.2-bb.0
appVersion: 2025.4.2
keywords:
- coverage
- security
- code
- quality
home: https://www.sonarqube.org/
icon: https://raw.githubusercontent.com/SonarSource/sonarqube-static-resources/master/helm/SonarQubeServerLogo.png
sources:
- https://github.com/SonarSource/helm-chart-sonarqube
- https://github.com/SonarSource/docker-sonarqube
- https://github.com/SonarSource/sonarqube
kubeVersion: '>= 1.24.0-0'
annotations:
  bigbang.dev/maintenanceTrack: bb_integrated
  bigbang.dev/upstreamReleaseNotesMarkdown: |
    - [Find our upstream chart's CHANGELOG here](https://github.com/SonarSource/helm-chart-sonarqube/blob/sonarqube-2025.3.1-sonarqube-dce-2025.3.1/charts/sonarqube/CHANGELOG.md)
    - [and our upstream application release notes here](https://github.com/SonarSource/helm-chart-sonarqube/blob/sonarqube-2025.3.1-sonarqube-dce-2025.3.1/charts/sonarqube/README.md)
  bigbang.dev/applicationVersions: |
    - Sonarqube: 25.7.0.110598-community
  helm.sh/images: |
    - name: sonarqube
      image: registry1.dso.mil/ironbank/sonarsource/sonarqube/sonarqube-community-build:25.8.0.112029-community
    - name: base
      image: registry1.dso.mil/ironbank/big-bang/base:2.1.0
    - name: postgresql
      condition: postgresql.enabled
      image: registry1.dso.mil/ironbank/opensource/postgres/postgresql:16.2
    - name: ubi9
      image: registry1.dso.mil/ironbank/redhat/ubi/ubi9:9.6
dependencies:
- name: sonarqube
  version: '2025.4.2'
  repository: 'https://SonarSource.github.io/helm-chart-sonarqube'
  alias: upstream
- name: gluon
  version: '0.9.0'
  repository: 'oci://registry1.dso.mil/bigbang'