apiVersion: v1
name: sonarqube
description: SonarQube offers Code Quality and Code Security analysis for up to 27 languages. Find Bugs, Vulnerabilities, Security Hotspots and Code Smells throughout your workflow.
version: 1.0.31-bb.3
appVersion: 8.9.10
keywords:
  - coverage
  - security
  - code
  - quality
home: https://www.sonarqube.org/
icon: https://www.sonarqube.org/assets/logo-31ad3115b1b4b120f3d1efd63e6b13ac9f1f89437f0cf6881cc4d8b5603a52b4.svg
sources:
  - https://github.com/SonarSource/docker-sonarqube
maintainers:
  - name: rjkernick
    email: rjkernick@gmail.com
  - name: tsiddique
    email: tsiddique@live.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Updated SonarQube to 8.9.10"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: sonarqube
      image: sonarqube:8.9.10-community
  bigbang.dev/applicationVersions: |
    - Sonarqube: 8.9.10-community
  # base image used for curlContainerImage override if admin.password is set
  helm.sh/images: |
    - name: sonarqube
      image: registry1.dso.mil/ironbank/big-bang/sonarqube:8.9.10-community
    - name: base
      image: registry1.dso.mil/ironbank/big-bang/base:2.0.0
    - name: postgresql12
      condition: postgresql.enabled
      image: registry1.dso.mil/ironbank/opensource/postgres/postgresql12:12.13


