namespace: sonarqube

commonLabels:
  app: sonarqube

resources:
  - namespace.yaml
  - all.yaml

configMapGenerator:
  - name: sonarqube-properties
    namespace: sonarqube
    files:
      - sonar.properties
images:
  - name: registry.dsop.io/platform-one/apps/sonarqube:8.4-0.1.0
    newName: registry.dsop.io/platform-one/apps/sonarqube-ib
    newTag: 8.3-community-ib-bb



