{{- /* Adds additional sonarqube policies based on values */ -}}
{{- if and .Values.networkPolicies.enabled (eq .Release.Namespace "sonarqube") }}
{{- range $policy := .Values.networkPolicies.additionalPolicies -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $policy.name }}
spec:
  {{ tpl ($policy.spec | toYaml) $ | nindent 2 }}
---
{{- end }}
{{- end }}


