{{- if and .Values.istio.enabled .Values.istio.hardened.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-http-policy
  namespace: {{ .Release.Namespace }}
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        ports: 
        - "9000"
        - "9001"
{{- end }}
