{{- if .Values.prometheusMonitoring.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "sonarqube.name" . }}
  {{- if .Values.prometheusMonitoring.podMonitor.namespace }}
  namespace: {{ .Values.prometheusMonitoring.podMonitor.namespace | quote }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    app: {{ template "sonarqube.name" . }}
spec:
   {{- if .Values.prometheusMonitoring.podMonitor.jobLabel }}
  jobLabel: {{ .Values.prometheusMonitoring.podMonitor.jobLabel | quote }}
  {{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ template "sonarqube.name" . }}
  endpoints:
  - port: http
    path: {{ include "sonarqube.webcontext" . }}api/monitoring/metrics
    scheme: https
    {{- if .Values.prometheusMonitoring.podMonitor.interval }}
    interval: {{ .Values.prometheusMonitoring.podMonitor.interval }}
    {{- end }}
    {{- if .Values.prometheusMonitoring.podMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.prometheusMonitoring.podMonitor.scrapeTimeout }}
    {{- end }}
    bearerTokenSecret:
    {{- if and .Values.monitoringPasscodeSecretName .Values.monitoringPasscodeSecretKey }}
      name: {{ .Values.monitoringPasscodeSecretName }}
      key: {{ .Values.monitoringPasscodeSecretKey }}
    {{- else }}
      name: {{ template "sonarqube.fullname" . }}-monitoring-passcode
      key: SONAR_WEB_SYSTEMPASSCODE
    {{- end }}
    {{- if .Values.istio.enabled }}
    tlsConfig:
      caFile: /etc/prom-certs/root-cert.pem
      certFile: /etc/prom-certs/cert-chain.pem
      keyFile: /etc/prom-certs/key.pem
      insecureSkipVerify: true
    {{ end }}
{{- end }}
